### ISSUE TITLE
Backend deployment fails

### ISSUE THREAD

**Issue by MikeCodesDotNET** [MikeCodesDotNET/Beer-Drinkin#3]
## Error

Cannot create more than one clustered index on table 'dbo.BeerItems'. Drop the existing clustered index 'PK_dbo.BeerItems' before creating another.

From speaking with the web team, it seems Azure SQL doesn't support clustered Indexes.

**Comment by seesharprun** [comment]
Based on this article, you have to use a special type of database initializer.

https://azure.microsoft.com/en-us/documentation/articles/mobile-services-dotnet-backend-how-to-use-code-first-migrations/#using-code-first-migrations-without-an-initializer

The default database initializer tried to create a clustered index for **Id** and **CreatedAt**. Azure SQL Database only supports a single clustered index for the table.
